### ISSUE TITLE
Can use axios-interceptor when import by HttpModule.register or HttpModule.registerAsync

### ISSUE THREAD

**Issue by zjy01** [narando/nest-axios-interceptor#277]
I using nest-axios-interceptor like this
```ts
@Module({
  imports: [
    HttpModule,
    HomeModule,
  ],
  providers: [
    LoggingAxiosInterceptor,
  ],
})
export class AppModule {}
```

it was useful when import HttpModule.
but  if i use HttpModule.register, LoggingAxiosInterceptor not work
```ts

@Module({
  imports: [
    HttpModule.register({
       timeout: 10000
    })
  ],
})
export class HttpModule {}
```

**Comment by apricote** [comment]
Can you create an example repository that reproduces your issue?

**Comment by apricote** [comment]
I just tried it with `HttpModule.registerAsync` and it worked as expected. Please reopen the issue if it still persists for you, it would be greated if you have an example repository with a reproduction of the issue.
