### ISSUE TITLE
Update @nestjs/axios to version 0.1.1

### ISSUE THREAD

**Issue by JwanKhalaf** [narando/nest-axios-interceptor#344]
Currently `"@nestjs/axios": ">=0.0.5 <=0.0.8"` is stopping [next-xray](https://github.com/narando/nest-xray) from installing too because a [pull request from chore to update the dependency is failing](https://github.com/narando/nest-xray/pull/350).

**Comment by apricote** [comment]
This is already prepared and awaiting review in !341
