### ISSUE TITLE
Using latest version of nestjs/axios 1.0.0

### ISSUE THREAD

**Issue by RezaRahmati** [narando/nest-axios-interceptor#379]
Nestjs released "@nestjs/axios": "^1.0.0",

In package.json nestjs/axios is limited to  @nestjs/axios@">=0.0.5 <=0.1.0" which causing issue on the pipeline as either we need to install using --force or --legacy-peer-depency

**Comment by ashutosh-datar** [comment]
When it can be resolved?

**Comment by lzkill** [comment]
I confirm this is keeping the project from being used with nestjs v9.

**Comment by tiagomichaelsousa** [comment]
Also looking forward to the update of axios 🚀

**Comment by okonon** [comment]
Same here. It would be great to get this fixed.

**Comment by apricote** [comment]
I do not have the time to look at this. Checkout #386 for the issues blocking the upgrade. You can create a PR if you have a fix for the issue.
